# Generated by Django 5.0.4 on 2024-05-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("modulo_inventario", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="location",
            name="address",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
